---
- hosts: localhost
  connection: local

  tasks:
  - name: Install build prerequisites
    become: true
    package: 
      name: 
         - ninja-build 
         - gettext 
         - libtool 
         - libtool-bin 
         - autoconf 
         - automake 
         - cmake 
         - g++ 
         - pkg-config 
         - unzip 
         - curl 
         - doxygen
      state: latest
       
  - name: Git clone the neovim 
    become: false
    ansible.builtin.git:
      repo: 'https://github.com/neovim/neovim.git'
      dest: "{{ lookup('env', 'PWD') }}/neovim"
      version: nightly

  - name: Build neovim
    shell: "cd {{ lookup('env', 'PWD') }}/neovim && make -j 20 CMAKE_BUILD_TYPE=RelWithDebInfo"
    tags:
      - neovim

  - name: Install neovim
    become: true
    shell: "cd {{ lookup('env', 'PWD') }}/neovim && make install"
    tags:
      - neovim

  - name: Create config directory for nvim
    ansible.builtin.file:
      path: "{{ lookup('env', 'PWD') }}/.config/nvim"
      state: directory
      owner: korros
      group: korros
      mode: '0775'

  - name: Git clone the neovim kickstart
    ansible.builtin.git:
      repo: 'https://github.com/nvim-lua/kickstart.nvim.git'
      dest: "{{ lookup('env', 'PWD') }}/kickstart.nvim"

  - name: Copy kickstart.nvim init.lua to proper config directory
    copy:
      src: "{{ lookup('env', 'PWD') }}/kickstart.nvim/init.lua"
      dest: "{{ lookup('env', 'PWD') }}/.config/nvim/init.lua"
      owner: korros
      group: korros
      mode: '0775'
