---
- name: Local playbook run for setting up Neovim
  hosts: localhost
  become: True

  vars:
    ansible_conneciton: local
    ansible_python_interpreter: "{{ ansible_playbook_python }}"
    tmp_build: "/tmp/build"
    my_home: "/home/korros"
    my_user: "korros"

  tasks:
  - name: Create config directory for nvim
    ansible.builtin.file:
      path: "{{ tmp_build }}"
      state: directory
      mode: "0775"

  - name: Install build prerequisites
    package: 
      name: 
         - ninja-build 
         - gettext 
         - libtool 
         - libtool-bin 
         - autoconf 
         - automake 
         - cmake 
         - g++ 
         - pkg-config 
         - unzip 
         - curl 
         - doxygen
      state: latest
       
  - name: Git clone the neovim 
    ansible.builtin.git:
      repo: 'https://github.com/neovim/neovim.git'
      dest: "{{ tmp_build }}/neovim"
      version: stable

  - name: Build neovim
    shell: "cd {{ tmp_build }}/neovim && make -j 20 CMAKE_BUILD_TYPE=RelWithDebInfo"

  - name: Install neovim
    shell: "cd {{ tmp_build }}/neovim && make install"

  - name: Create config directory for nvim
    ansible.builtin.file:
      path: "{{ my_home }}/.config/nvim"
      state: directory
      owner: "{{ my_user }}"
      group: "{{ my_user }}"
      mode: "0775"

####
# Playbook info from https://kyle.pericak.com/nodejs-ansible.html
####

  - name: "Add nodejs apt key"
    apt_key:
      url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
      state: present

  - name: "Add nodejs 19.x ppa for apt repo"
    apt_repository:
      repo: deb https://deb.nodesource.com/node_19.x/ jammy main
      update_cache: yes

  - name: Install kickstart lsp requirements
    package: 
      update_cache: yes
      name: 
         - nodejs
         - cargo
         - golang-go
         - python3-pip
         - python3-venv
         - ripgrep
      state: latest

  - name: Clone the neovim kickstart repo
    ansible.builtin.git:
      repo: 'https://github.com/nvim-lua/kickstart.nvim.git'
      dest: "{{ tmp_build }}/kickstart.nvim"

  - name: Copy kickstart.nvim init.lua to proper config directory
    copy:
      src: "{{ tmp_build }}/kickstart.nvim/init.lua"
      dest: "{{ my_home }}/.config/nvim/init.lua"
      owner: "{{ my_user }}"
      group: "{{ my_user }}"
      mode: "0775"
