---
- hosts: localhost
  connection: local
  vars:
    my_home_dir: "/home/korros"

  tasks:
  - name: Install build prerequisites
    become: true
    package: 
      name: 
         - ninja-build 
         - gettext 
         - libtool 
         - libtool-bin 
         - autoconf 
         - automake 
         - cmake 
         - g++ 
         - pkg-config 
         - unzip 
         - curl 
         - doxygen
      state: latest
       
  - name: Git clone the neovim 
    become: false
    ansible.builtin.git:
      repo: 'https://github.com/neovim/neovim.git'
      dest: "{{ my_home_dir }}/neovim"
      version: nightly

  - name: Build neovim
    become: true
    shell: "cd {{ my_home_dir }}/neovim && make -j 20 CMAKE_BUILD_TYPE=RelWithDebInfo"
    tags:
      - neovim

  - name: Install neovim
    become: true
    shell: "cd {{ my_home_dir }}/neovim && make install"
    tags:
      - neovim

  - name: Create config directory for nvim
    become: false
    ansible.builtin.file:
      path: "{{ my_home_dir }}/.config/nvim"
      state: directory
      owner: korros
      group: korros
      mode: '0775'

  - name: Git clone the neovim kickstart
    become: false
    ansible.builtin.git:
      repo: 'https://github.com/nvim-lua/kickstart.nvim.git'
      dest: "{{ my_home_dir }}/kickstart.nvim"

  - name: Copy kickstart.nvim init.lua to proper config directory
    become: false
    copy:
      src: "{{ my_home_dir }}/kickstart.nvim/init.lua"
      dest: "{{ my_home_dir }}/.config/nvim/init.lua"
      owner: korros
      group: korros
      mode: '0775'
  
  - name: Create admin user
    user:
      name: stark
      comment: Stark Admin
      password: "$6$MakingCo0lS@ltz$PixtIdE7Cw21mxk97FFNjoZDBvv5Cg8Hdh8Ba1A2Q2hqhiSUkTGtdiBhmSMh3j984q7sxckyz408UJOk3ygcF/"
      system: yes

  - name: Setup sudo for stark
    copy:
      src: files/sudoer_stark
      dest: /etc/sudoers.d/stark
      owner: root
      group: root
      mode: 0440

  - name: Add ansible-pull cron job
    cron:
        name: Ansible auto-provision
        user: stark
        minute: "*/10"
        job: ansible-pull -o -U https://github.com/KoRRoS83/ansible_desktop.git
